### ISSUE TITLE
关于关闭置顶栏的建议

### ISSUE THREAD

**Issue by wyl219** [aeagean/WindowTop#4]
现在的置顶栏对我来说很碍事,而且也没什么用处,只能在任务栏图标上右键关闭,下次重启后又会出现,希望能永久性的关闭.
另外,在软件内点击商店购买,弹出窗口提示失败,不知道怎么回事.

**Comment by aeagean** [comment]
最新版本3.2.1支持永久性关闭置顶栏了。如果商店购买不了，可以使用注册码激活。
